variable "vpc_id" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "cluster_id" {}
variable "cluster_endpoint" {}
variable "redis_enpoint" {}
variable "postgres_endpoint" {}
variable "alb_dns_name" {}
variable "postgres_security_group" {}
variable "k8s_managed_node_security_group" {}
variable "alb_security_group" {}
variable "k8s_kms_arn" {}
